name: ラベルの自動作成

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手動でも実行可能

permissions:
  contents: write

jobs:
  create-labels:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Create labels if they don't exist
        run: |
          # ラベル名、色、説明文の定義
          labels=(
            "レビュー待ち:#ffcc00:レビューが必要なPR"
          )

          # ラベルの作成
          for label_info in "${labels[@]}"; do
            IFS=":" read -r label color description <<< "$label_info"
            if ! gh label list | grep -q "$label"; then
              gh label create "$label" --color "$color" --description "$description"
            else
              echo "$label already exists, skipping creation."
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
